In [3]:
%pip install openpyxl
!pip install datatime

Requirement already satisfied: openpyxl in c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Could not find a version that satisfies the requirement datatime (from versions: none)
ERROR: No matching distribution found for datatime

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: C:\Users\ASUS\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

In [2]:
import yfinance as yf
import openpyxl
import pandas as pd
from datetime import date
datos_yahoo = pd.read_excel("../config/SP500_yfinance.xlsx")

sectores = datos_yahoo.groupby("Sector")["Ticket"].apply(list).to_dict()
acciones = datos_yahoo["Ticket"].to_list()
precios = yf.download(acciones, start="2026-01-01", end=str(date.today()), progress=False)["Close"]

$BF.B: possibly delisted; no price data found  (1d 2026-01-01 -> 2026-08-27)
$BRK.B: possibly delisted; no timezone found

2 Failed downloads:
['BF.B']: possibly delisted; no price data found  (1d 2026-01-01 -> 2026-08-27)
['BRK.B']: possibly delisted; no timezone found

In [3]:
def datos_sector(ticket_sector,df_precios):
    tickets = [t for t in ticket_sector if t in df_precios.columns]
    return df_precios[tickets]

In [4]:
datos_por_sector ={}
rendimientos_por_sector = {}
covarianzas_por_sector = {}

for sector, tickets in sectores.items():
    precio = datos_sector(tickets,precios)
    datos_por_sector[sector]=precio

    if not precio.empty:
        rendimientos = precio.pct_change().dropna()
        rendimientos_por_sector[sector]=rendimientos

        covarianzas_por_sector[sector]=rendimientos.cov()*252

c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\numpy\lib\_function_base_impl.py:576: RuntimeWarning: Mean of empty slice
  avg = a.mean(axis, **keepdims_kw)
c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\numpy\_core\_methods.py:134: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\pandas\core\frame.py:13300: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\numpy\lib\_function_base_impl.py:2888: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
c:\Users\ASUS\AppData\Local\Programs\Python\Python314\Lib\site-packages\numpy\lib\_function_base_impl.py:2888: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

In [12]:
datos_por_sector["Industrials"].round(2)

Ticker,ADP,ALLE,AME,AOS,AXON,BA,BLDR,BR,CARR,CAT,...,UBER,UNP,UPS,URI,VLTO,VRSK,VRT,WAB,WM,XYL
Date,,,,,,,,,,,,,,,,,,,,,
2026-01-02,248.92,159.65,208.50,67.19,563.45,227.77,104.63,217.79,52.91,594.78,...,82.86,229.51,96.44,839.97,98.21,219.86,175.53,215.53,216.60,136.11
2026-01-05,253.29,160.61,210.66,67.38,591.16,228.13,108.44,220.11,53.18,612.36,...,80.74,229.57,97.38,881.67,98.89,219.54,173.87,216.26,217.63,137.99
2026-01-06,257.03,160.57,213.50,67.52,626.65,229.84,111.26,219.00,52.89,619.31,...,85.54,231.20,100.45,886.73,99.64,220.07,174.87,220.18,217.27,140.30
2026-01-07,257.17,157.77,210.53,66.01,620.91,228.12,105.05,216.80,51.97,592.90,...,86.19,222.16,100.63,875.58,100.01,218.46,171.46,215.87,214.19,138.42
2026-01-08,261.51,162.98,209.39,69.24,612.98,227.38,111.29,220.20,53.25,604.44,...,87.59,227.47,102.12,912.34,101.44,221.68,160.71,221.67,216.06,139.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-20,279.21,161.72,239.08,62.43,614.26,215.10,70.32,178.50,60.15,815.39,...,78.55,303.97,102.58,1095.26,99.46,187.68,264.63,292.31,224.92,113.44
2026-08-21,280.81,162.31,239.55,63.08,627.75,214.20,70.21,182.18,60.37,827.90,...,78.80,308.05,102.01,1098.51,98.77,187.50,261.95,297.57,224.06,113.42
2026-08-24,283.01,162.63,242.33,62.72,597.59,210.46,70.22,185.45,59.97,811.02,...,79.29,309.86,102.72,1083.56,99.37,189.55,254.97,297.62,226.46,114.18
2026-08-25,282.78,160.37,241.77,62.15,613.26,211.08,69.36,184.82,58.52,811.29,...,80.35,309.59,105.14,1053.14,98.77,188.49,255.75,296.94,222.13,112.81
2026-08-26,281.39,160.28,245.20,62.48,607.48,212.09,68.67,181.60,58.74,821.93,...,78.49,310.62,105.65,1057.66,98.69,187.87,263.81,300.54,221.24,113.42

In [13]:
datos_por_sector["Financials"].round(2)

Ticker,ACGL,AFL,AIG,AIZ,AJG,ALL,AMP,AON,APO,ARES,...,SYF,TFC,TROW,TRV,USB,V,WFC,WRB,WTW,XYZ
Date,,,,,,,,,,,,,,,,,,,,,
2026-01-02,93.86,108.55,83.22,235.95,254.37,201.73,489.00,342.58,144.79,162.46,...,83.61,48.25,101.87,282.97,52.93,344.41,93.66,68.65,324.01,65.15
2026-01-05,94.44,110.47,83.33,238.63,261.57,203.46,502.98,349.57,147.90,168.05,...,85.67,48.97,103.68,285.52,54.46,351.69,94.82,69.99,332.28,68.45
2026-01-06,93.92,110.24,77.10,233.86,261.10,205.79,505.31,347.96,150.80,171.90,...,87.38,49.65,106.14,282.97,55.04,355.43,94.83,69.28,333.77,70.00
2026-01-07,95.16,108.50,76.11,234.74,257.35,205.15,493.22,348.21,142.49,166.83,...,86.35,49.07,103.21,280.99,53.85,353.76,92.76,67.79,329.08,71.47
2026-01-08,96.38,108.57,76.93,236.25,262.86,208.94,498.60,350.25,144.37,171.66,...,86.65,49.42,105.71,281.97,54.50,350.13,94.05,69.52,330.83,70.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-20,99.31,116.17,75.75,282.00,259.61,254.54,547.09,351.93,129.98,140.23,...,76.71,50.23,112.19,364.49,61.78,365.73,83.70,69.18,341.15,80.08
2026-08-21,99.39,116.07,76.12,284.04,263.81,253.83,555.59,355.11,132.69,141.25,...,79.47,50.42,111.51,363.58,62.05,371.04,83.84,68.60,341.99,82.16
2026-08-24,101.14,118.20,77.38,287.81,271.99,260.19,561.13,359.10,132.79,140.01,...,80.02,50.81,112.30,370.55,62.42,382.41,84.72,69.70,350.75,81.38
2026-08-25,100.56,116.18,76.38,285.15,268.51,257.62,560.26,354.83,133.18,142.76,...,80.77,50.30,112.87,369.66,62.41,384.14,84.79,68.48,346.82,82.72
2026-08-26,100.72,117.45,76.97,288.51,265.03,261.81,560.28,353.98,133.67,141.98,...,79.78,50.67,112.55,371.15,62.80,383.90,85.23,68.67,343.12,83.10

In [15]:
datos_por_sector["Information Technology"].round(2)

Ticker,AAPL,ACN,ADBE,ADI,ADSK,AKAM,AMAT,AMD,ANET,APH,...,TDY,TEL,TER,TRMB,TXN,TYL,VRSN,WDAY,WDC,ZBRA
Date,,,,,,,,,,,,,,,,,,,,,
2026-01-02,270.27,254.70,333.30,272.14,286.73,85.10,267.92,223.47,133.60,139.22,...,518.77,230.71,207.39,78.33,174.58,435.83,238.30,205.79,187.56,248.30
2026-01-05,266.53,258.65,331.56,275.67,288.66,85.91,283.31,221.08,137.19,139.39,...,524.09,228.91,219.33,79.27,174.24,441.10,237.04,208.90,187.74,252.64
2026-01-06,261.65,270.36,335.99,291.23,293.17,88.74,294.96,214.35,132.58,140.89,...,532.73,228.82,228.66,81.55,188.92,443.66,243.92,210.30,219.22,257.61
2026-01-07,259.62,268.45,338.10,291.18,293.79,88.18,291.16,210.02,130.08,138.43,...,531.48,227.12,222.30,80.18,182.64,448.23,241.52,211.14,199.73,246.96
2026-01-08,258.34,276.13,339.04,297.41,276.58,85.71,280.64,204.68,123.72,135.78,...,548.91,225.58,216.14,79.51,185.33,453.40,244.84,209.79,187.54,254.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-20,311.30,181.35,272.22,370.24,251.02,110.09,496.21,469.46,183.75,153.11,...,633.95,199.76,383.15,59.68,265.60,348.14,276.90,197.32,469.05,360.52
2026-08-21,309.35,185.28,275.30,373.09,253.83,110.42,492.32,473.25,188.65,157.01,...,636.15,203.52,375.74,60.25,264.36,350.73,281.80,200.01,459.44,368.51
2026-08-24,310.34,186.53,276.27,371.17,254.42,105.66,484.19,456.75,188.15,155.55,...,625.21,202.41,364.90,60.67,258.94,355.79,290.79,199.15,435.38,363.30
2026-08-25,309.90,186.93,273.92,373.66,251.21,105.74,480.04,479.18,190.94,158.78,...,626.90,201.41,366.43,59.43,260.05,350.06,293.75,194.42,450.75,360.52
2026-08-26,313.45,181.38,273.47,371.80,254.77,108.06,479.76,480.93,202.25,161.34,...,633.56,205.03,363.10,59.68,261.77,352.65,292.99,190.75,468.88,359.84

In [16]:
datos_por_sector["Health Care"].round(2)

Ticker,A,ABBV,ABT,ALGN,AMGN,BAX,BDX,BIIB,BMY,BSX,...,TMO,UHS,UNH,VEEV,VRTX,VTRS,WAT,WST,ZBH,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2026-01-02,137.13,224.01,121.92,156.03,321.07,19.48,151.22,177.82,52.32,94.71,...,591.33,219.36,331.91,219.49,452.13,12.17,381.96,275.76,89.54,123.98
2026-01-05,142.08,215.09,124.14,160.13,314.29,19.87,154.33,174.63,51.93,95.48,...,609.98,222.35,337.45,221.32,448.80,12.09,394.97,278.38,92.15,127.37
2026-01-06,146.98,218.76,125.45,167.66,323.55,20.53,159.30,182.61,53.26,97.79,...,619.49,221.22,344.31,237.87,468.38,12.11,400.54,280.18,94.24,127.35
2026-01-07,147.19,228.03,124.72,166.81,334.79,20.38,157.24,186.91,55.51,98.65,...,615.92,207.90,337.14,239.35,484.15,12.17,399.41,277.79,92.17,123.73
2026-01-08,145.15,218.95,123.88,170.58,323.49,20.67,159.16,186.00,54.71,98.38,...,605.29,210.64,342.22,241.16,469.68,12.31,396.65,274.59,93.58,124.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-20,156.30,261.83,114.14,158.94,431.21,26.41,187.62,214.35,65.47,49.37,...,627.55,172.87,384.85,250.53,540.26,16.00,404.69,353.77,98.97,75.02
2026-08-21,159.00,264.96,116.64,162.55,439.33,26.34,192.00,216.78,67.01,50.37,...,629.27,177.26,390.11,247.90,548.05,16.32,410.70,353.08,100.98,77.73
2026-08-24,153.43,264.52,116.67,159.64,443.84,26.49,190.74,218.12,67.28,49.01,...,628.74,176.40,398.76,248.46,547.59,16.54,410.75,353.32,100.98,77.17
2026-08-25,154.77,265.79,116.13,159.61,442.24,26.29,189.78,220.77,67.92,49.86,...,628.15,175.76,396.59,246.78,552.85,16.72,414.44,348.48,100.24,77.29
2026-08-26,155.08,262.90,114.10,159.14,440.34,26.50,190.21,221.07,67.57,48.17,...,633.71,178.69,401.01,244.91,547.29,16.85,414.17,349.92,101.38,77.52

In [18]:
datos_por_sector["Consumer Discretionary"].round(2)

Ticker,ABNB,AMZN,APTV,AZO,BBY,BKNG,CCL,CMG,CVNA,DASH,...,ROST,SBUX,TJX,TPR,TSCO,TSLA,ULTA,WSM,WYNN,YUM
Date,,,,,,,,,,,,,,,,,,,,,
2026-01-02,133.01,226.50,78.44,3303.82,67.25,211.91,30.43,37.49,80.05,219.79,...,182.00,82.47,152.86,128.36,49.85,438.07,620.04,185.90,121.68,149.07
2026-01-05,135.87,233.06,80.52,3268.30,68.09,213.67,30.99,38.25,86.01,226.72,...,185.92,85.02,152.42,127.82,48.87,451.67,631.15,189.77,118.82,148.87
2026-01-06,138.02,240.93,82.61,3244.92,70.15,212.91,31.79,38.62,88.09,229.38,...,186.77,87.86,152.50,132.45,49.34,432.96,650.06,194.95,119.66,149.98
2026-01-07,137.04,241.56,82.15,3318.08,66.91,216.79,31.60,38.87,90.16,230.52,...,186.23,85.14,152.62,130.25,48.93,431.41,655.36,189.84,115.53,149.07
2026-01-08,138.66,246.29,86.45,3313.99,69.80,216.76,31.19,39.18,88.52,224.10,...,188.50,86.61,156.79,132.78,50.41,435.80,657.46,195.75,117.42,152.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-20,185.00,260.11,47.03,2961.99,85.73,209.87,25.37,35.29,71.52,222.36,...,228.99,103.99,140.69,129.82,34.81,345.13,515.14,235.70,99.60,152.33
2026-08-21,187.30,258.63,48.28,2957.95,85.89,209.62,25.73,36.90,69.91,223.49,...,239.04,107.08,140.53,130.17,34.74,362.86,521.46,237.58,100.28,152.99
2026-08-24,190.21,262.07,47.34,3009.44,87.48,213.36,25.71,38.02,72.33,229.06,...,241.52,107.49,140.71,132.16,35.92,348.95,538.76,237.77,99.41,157.35
2026-08-25,190.50,261.06,46.63,3027.34,85.29,213.78,26.14,37.43,75.77,233.50,...,241.19,105.76,139.48,130.12,35.38,350.25,537.22,234.74,98.74,156.27
2026-08-26,188.07,260.28,46.27,2999.00,87.44,208.89,25.59,37.34,73.95,236.93,...,236.27,108.49,136.83,130.25,35.01,345.82,543.19,237.43,97.17,154.41

In [19]:
datos_por_sector["Consumer Staples"].round(2)

Ticker,ADM,BF.B,BG,CASY,CHD,CL,CLX,COST,DG,DLTR,...,PEP,PG,PM,SJM,STZ,SYY,TAP,TGT,TSN,WMT
Date,,,,,,,,,,,,,,,,,,,,,
2026-01-02,57.86,NaN,90.99,554.94,81.87,76.30,97.37,850.75,134.91,127.70,...,139.50,138.70,157.58,93.74,138.24,71.60,46.36,97.82,57.09,112.05
2026-01-05,58.38,NaN,91.73,562.92,83.32,75.56,97.78,871.89,136.99,128.57,...,137.24,137.31,157.14,91.74,139.55,71.77,45.30,99.36,56.20,112.00
2026-01-06,59.27,NaN,92.68,562.50,84.72,75.82,97.13,885.19,143.28,133.78,...,136.30,136.86,152.52,93.05,140.67,72.00,45.18,101.50,55.06,113.62
2026-01-07,57.34,NaN,90.94,572.25,83.10,75.71,98.24,878.70,142.11,131.56,...,134.38,135.03,152.51,92.63,137.57,71.11,44.93,100.89,55.28,112.01
2026-01-08,59.95,NaN,95.77,584.99,85.06,79.43,100.65,911.29,142.59,131.61,...,136.70,138.45,156.11,94.90,144.89,73.23,46.22,103.48,56.43,112.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-20,81.70,NaN,116.57,828.38,97.41,89.70,106.04,933.51,120.58,128.45,...,142.08,142.97,191.52,123.05,134.14,83.06,42.61,158.25,58.40,103.59
2026-08-21,80.30,NaN,113.11,835.74,98.80,91.08,106.69,947.74,123.41,131.48,...,143.48,144.68,188.23,124.32,135.66,84.10,42.94,165.44,58.48,103.70
2026-08-24,78.16,NaN,110.16,854.21,102.53,92.55,107.17,971.40,125.33,136.75,...,144.67,146.60,191.46,125.87,137.60,83.86,42.99,169.89,57.87,106.49
2026-08-25,79.16,NaN,111.71,824.92,102.56,91.33,104.93,960.01,122.58,134.48,...,142.27,145.40,193.92,125.45,135.01,83.46,42.01,163.47,57.17,105.38
2026-08-26,80.09,NaN,113.25,807.12,102.86,92.06,104.23,956.12,122.78,132.18,...,142.19,145.00,194.10,130.90,134.45,83.27,42.09,164.04,56.55,104.34

In [33]:
import yfinance as yf
accion = yf.download(tickers="BFb",start="2010-01-01",end=date.today())

$BFB: possibly delisted; no timezone found
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BFB']: possibly delisted; no timezone found

In [20]:
datos_por_sector["Utilities"].round(2)

Ticker,AEE,AEP,AES,ATO,AWK,CEG,CMS,CNP,D,DTE,...,NRG,PCG,PEG,PNW,PPL,SO,SRE,VST,WEC,XEL
Date,,,,,,,,,,,,,,,,,,,,,
2026-01-02,99.48,113.21,14.30,166.47,127.67,364.63,68.80,38.08,58.03,128.32,...,164.55,16.18,79.65,85.74,34.57,85.09,88.46,164.77,103.78,73.58
2026-01-05,98.24,111.51,14.21,164.04,124.81,353.37,67.87,37.46,57.50,126.79,...,160.03,16.04,78.03,85.31,34.25,84.79,86.32,162.48,102.75,72.98
2026-01-06,99.23,112.46,14.37,164.68,126.35,353.01,68.76,37.60,57.52,128.01,...,158.09,16.06,77.30,86.82,34.35,85.42,86.47,169.06,103.27,73.33
2026-01-07,97.71,111.15,13.94,163.32,124.69,337.13,67.96,37.12,55.92,126.26,...,147.47,15.42,76.30,85.02,33.91,84.20,85.15,154.17,102.38,72.14
2026-01-08,98.18,113.33,13.72,164.25,126.65,321.12,68.25,37.36,56.62,127.60,...,142.14,15.63,76.15,86.88,34.14,85.13,86.80,150.18,102.57,72.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-20,108.79,125.70,14.77,169.50,137.21,272.92,69.83,40.20,67.47,138.15,...,115.36,17.96,74.62,99.38,35.20,91.43,87.38,138.94,108.51,78.71
2026-08-21,106.13,120.94,14.77,165.85,135.39,272.88,68.27,38.77,66.60,135.22,...,113.11,17.60,72.61,97.36,34.38,88.94,82.89,136.21,106.01,76.30
2026-08-24,107.16,121.98,14.75,167.82,139.91,273.43,68.42,39.10,66.61,135.66,...,111.78,18.11,73.53,97.71,35.04,90.10,84.57,135.66,107.58,77.33
2026-08-25,106.83,122.77,14.73,167.56,137.60,278.42,68.74,38.93,66.93,136.14,...,113.61,18.36,73.28,97.67,34.99,89.97,84.03,139.03,106.67,77.19
2026-08-26,107.75,123.36,14.73,169.46,137.49,279.52,69.23,39.59,66.91,137.71,...,116.14,18.22,74.03,98.69,35.02,89.76,85.28,140.03,107.52,77.68

In [21]:
datos_por_sector["Materials"].round(2)

Ticker,ALB,AMCR,APD,AVY,BALL,CF,CRH,CTVA,DOW,ECL,...,MLM,MOS,NEM,NUE,PKG,PPG,SHW,STLD,SW,VMC
Date,,,,,,,,,,,,,,,,,,,,,
2026-01-02,143.21,40.83,247.37,180.38,53.00,78.97,125.04,67.45,23.74,261.23,...,632.76,24.56,100.78,168.41,208.51,102.44,325.52,175.12,38.46,290.98
2026-01-05,145.40,41.07,250.70,178.51,53.55,79.10,126.89,67.54,24.36,261.76,...,640.30,24.41,103.08,167.15,208.52,103.29,329.85,170.91,38.92,294.97
2026-01-06,157.36,41.60,255.17,179.99,53.94,78.30,127.44,69.06,24.97,270.07,...,644.53,24.70,108.73,168.36,209.10,103.71,337.68,171.82,39.77,298.14
2026-01-07,160.76,40.78,258.63,178.50,53.18,76.37,121.52,68.23,24.26,267.30,...,623.38,24.84,107.54,163.85,204.25,102.00,329.06,166.93,38.50,290.45
2026-01-08,157.52,42.09,257.99,183.92,54.47,80.16,123.27,69.82,25.36,270.28,...,636.42,25.99,106.43,166.90,211.23,103.38,338.61,171.24,41.08,297.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-20,134.19,47.81,300.33,182.68,62.61,125.70,93.09,79.46,32.90,281.48,...,525.27,23.35,127.64,240.48,249.56,112.44,346.11,219.00,48.19,270.67
2026-08-21,143.25,48.59,305.10,183.71,63.59,129.60,95.07,81.79,32.35,281.63,...,534.92,24.41,131.58,243.63,252.79,113.63,346.59,228.68,49.39,276.04
2026-08-24,141.51,47.91,306.24,183.69,64.42,129.24,95.79,82.81,31.44,286.98,...,533.11,24.00,131.84,244.64,248.88,113.23,346.73,229.27,48.69,275.94
2026-08-25,133.18,47.27,303.85,179.95,64.08,127.26,96.20,83.05,30.16,289.54,...,531.74,24.27,135.14,247.55,246.54,113.65,350.45,231.08,49.43,274.09
2026-08-26,134.51,47.15,306.66,182.33,64.05,125.70,97.05,82.88,30.33,290.60,...,532.18,24.16,131.60,252.80,246.68,114.42,348.66,235.90,49.56,273.74

In [22]:
datos_por_sector["Communication Services"].round(2)

Ticker,APP,CHTR,CMCSA,DIS,ECHO,FOX,FOXA,GOOG,GOOGL,LYV,...,OMC,PSKY,RDDT,T,TKO,TMUS,TTD,TTWO,VZ,WBD
Date,,,,,,,,,,,,,,,,,,,,,
2026-01-02,618.32,209.28,26.69,111.00,112.18,65.61,73.40,314.91,314.74,145.31,...,79.66,13.05,241.89,23.71,205.31,197.55,37.68,251.60,38.58,28.51
2026-01-05,632.91,210.01,27.12,113.20,110.67,67.40,75.30,316.91,316.13,145.31,...,76.76,12.85,244.05,23.85,202.05,198.82,40.11,257.31,38.30,28.53
2026-01-06,617.24,210.62,26.43,113.70,116.06,67.37,75.74,314.14,313.93,145.52,...,78.01,12.38,253.81,23.49,201.21,196.58,39.74,254.35,38.37,28.47
2026-01-07,632.92,206.36,26.89,112.05,112.16,66.71,74.66,322.01,321.56,143.96,...,76.00,12.25,255.50,23.14,201.31,195.29,38.65,256.67,38.21,28.59
2026-01-08,616.53,209.71,27.19,113.30,116.95,67.19,75.32,325.58,325.02,147.27,...,77.19,12.15,253.95,23.33,200.50,195.90,37.30,252.38,38.63,28.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-20,308.77,147.76,26.42,107.32,86.92,60.45,67.96,338.20,340.67,182.02,...,87.07,10.29,150.31,25.15,195.45,181.22,13.32,240.15,49.19,28.23
2026-08-21,305.77,150.17,26.85,107.78,86.81,61.05,68.54,341.75,344.82,181.82,...,87.54,10.35,153.29,25.29,193.14,183.04,13.18,239.62,49.45,28.55
2026-08-24,298.59,150.30,27.02,110.61,85.32,61.59,69.21,344.59,348.06,184.59,...,88.94,10.35,152.70,25.69,193.42,182.62,13.27,233.50,50.15,28.70
2026-08-25,310.54,155.14,27.10,111.25,86.52,62.69,70.33,343.34,346.96,186.77,...,88.20,10.67,162.45,25.77,193.41,181.61,13.25,232.93,50.25,28.90
2026-08-26,308.11,153.89,27.20,109.63,85.61,62.23,69.60,339.10,342.00,182.64,...,87.89,10.74,155.36,25.87,187.90,179.61,13.03,233.45,50.19,28.75

In [23]:
datos_por_sector["Energy"].round(2)

Ticker,APA,BKR,COP,CVX,DVN,EOG,EQT,EXE,FANG,HAL,...,MPC,OKE,OXY,PSX,SLB,TPL,TRGP,VLO,WMB,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2026-01-02,24.78,46.63,94.61,151.66,37.41,104.66,52.99,107.87,149.78,29.33,...,163.24,71.61,41.99,127.89,39.76,297.17,184.05,162.90,59.97,120.24
2026-01-05,23.91,48.54,97.06,159.40,36.10,103.62,52.88,104.97,144.52,31.63,...,172.93,70.95,40.85,137.11,43.32,296.75,180.80,177.94,60.28,122.89
2026-01-06,23.33,48.85,95.02,152.29,35.45,102.45,52.94,103.60,142.04,30.55,...,168.46,68.27,41.35,133.85,43.15,293.03,175.32,175.67,58.64,118.67
2026-01-07,22.85,48.32,91.91,150.98,34.05,100.06,54.01,104.81,138.09,30.11,...,170.53,68.13,40.61,135.05,41.90,280.64,172.01,181.18,59.52,116.16
2026-01-08,24.79,49.66,96.59,154.92,35.65,103.00,51.74,102.49,145.18,31.88,...,175.04,69.68,42.83,141.26,43.94,302.14,174.19,188.53,60.27,120.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-20,44.39,62.78,134.89,205.77,49.30,152.19,53.89,96.07,211.02,35.69,...,358.23,94.60,61.52,240.00,53.55,369.56,302.25,341.51,71.68,166.15
2026-08-21,43.39,62.34,134.87,205.27,49.10,153.05,53.72,96.09,210.72,35.34,...,360.72,93.33,61.30,242.87,53.87,383.64,299.10,348.86,70.49,165.11
2026-08-24,42.96,61.99,133.35,203.09,48.23,150.21,53.79,96.33,205.60,34.63,...,362.52,93.02,60.11,241.96,54.00,373.45,294.26,346.00,70.97,164.05
2026-08-25,41.35,61.82,131.84,199.89,46.91,146.83,54.00,94.66,199.89,33.80,...,354.88,91.70,58.41,236.90,53.29,372.79,286.91,340.41,71.08,160.64
2026-08-26,41.19,62.00,130.61,200.21,46.83,144.84,54.79,96.57,199.84,34.44,...,362.27,94.90,58.62,242.23,53.60,369.40,294.03,348.03,74.41,158.19

In [24]:
conteo_sector =(datos_yahoo["Sector"].value_counts().reset_index())
conteo_sector.columns = ["Sector","Cantidad_Acciones"]
conteo_sector = conteo_sector.sort_values(by="Cantidad_Acciones",ascending=False).reset_index(drop=True)
conteo_sector

                    Sector  Cantidad_Acciones
0              Industrials                 83
1               Financials                 76
2   Information Technology                 73
3              Health Care                 59
4   Consumer Discretionary                 47
5         Consumer Staples                 34
6                Utilities                 31
7              Real Estate                 30
8                Materials                 25
9   Communication Services                 24
10                  Energy                 21